# Generated by Django 4.0.3 on 2022-05-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
