# Generated by Django 4.0.3 on 2022-05-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_item_price_alter_item_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.TextField(max_length=5),
        ),
    ]
