# Generated by Django 4.0.3 on 2022-05-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer',
        ),
    ]
