# Generated by Django 4.0.3 on 2022-05-05 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='thumb',
        ),
    ]
