# Generated by Django 4.0.3 on 2022-05-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_item_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='thumb',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
