# Generated by Django 4.0.3 on 2022-05-05 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_item_thumb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='thumb',
            new_name='image',
        ),
    ]
