# Generated by Django 4.0.3 on 2022-05-05 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_thumb_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='Фото товара.svg', null=True, upload_to=''),
        ),
    ]
