# Generated by Django 4.0.3 on 2022-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BROWN'), (2, 'GREY'), (3, 'RED'), (4, 'YELLOW')], null=True),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[(1, 'S'), (2, 'M'), (3, 'L'), (4, 'XL'), (5, 'XLL')], max_length=3, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
