# Generated by Django 4.0.3 on 2022-05-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_cartitem_color_cartitem_size_delete_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='size',
            field=models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L'), ('xl', 'XL'), ('xll', 'XLL')], max_length=3, null=True),
        ),
    ]
