# Generated by Django 4.0.3 on 2022-05-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_category_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=20)),
                ('client_last_name', models.CharField(max_length=20, null=True)),
                ('client_phone_number', models.CharField(max_length=20)),
            ],
        ),
    ]
